# Generated by Django 5.0.6 on 2026-05-30 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pricehistory'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pricehistory',
            new_name='api_pricehi_product_aeef9d_idx',
            old_name='api_price_pr_product_idx',
        ),
    ]
