# Generated by Django 5.0.6 on 2026-05-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_api_price_pr_product_idx_api_pricehi_product_aeef9d_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(max_length=2048, unique=True),
        ),
    ]
