# Generated by Django 5.0.6 on 2026-05-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_increase_url_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertrackedproduct',
            name='last_alert_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='usertrackedproduct',
            name='last_alert_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
